### ISSUE TITLE
Colorscheme not being set to dark

### ISSUE THREAD

**Issue by ngerritsen** [jzone1366/twilight.nvim#1]
I am using the following `.lua` code to initialize the colorscheme, but it still results in loading the light colorscheme:

```lua
local status_ok, twilight = pcall(require, "twilight")
if not status_ok then
	return
end

twilight.setup({
	style = "dark", -- change the colorscheme to use dark
	styles = {
		comments = "italic", -- change style of comments to be italic
		keywords = "bold", -- change style of keywords to be bold
		functions = "italic,bold", -- styles can be a comma separated list
	},
})

twilight.load()
```

Also, the `:TwilightLoad` editor command is not being installed. I installed twilight using packer:

```lua
use 'jzone1366/twilight.nvim'
```

When printing:

```lua
vim.notify(require("twilight.config").options.style)
```

It does return `dark` and also when I change the style to rubbish like `xxx` it shows an error.

I also tried:

```lua
twilight.load("dark")
```

But no luck on that.

When looking at your code, I see the following in `colors/dark.lua`:

```lua
    bg         = "#FDFFFC",
    bg_alt     = "#E4E6E3",
```

That looks like a light background. Might that be the issue?

If you need more info let me know!

**Comment by jzone1366** [comment]
Sorry. I need to update the dark. I've been using the light theme lately and made some updates. I'll finish that up and let you know.

**Comment by jzone1366** [comment]
This should be resolved now. Thanks for the Issue!
